### ISSUE TITLE
Extend from existing linker script?

### ISSUE THREAD

**Issue by stevefan1999-personal** [nbdd0121/unwinding#8]
Currently I use this to dump the used linker script to stdout and add in the eh_frames:
```toml
[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Wl,-verbose"
]
``` 
This worked ok but the problem is it is certainly not good accounting for multiple targets. For each build target we will need each linker script and that's a pretty big burden. Wonder if there is any possible way to extend from the existing linker script by patching or just stick it to some specific platforms as a setback?

PS: --eh-frame-hdr is broken in rust-lld. IDK why. I specified it directly in rustflags link-args, but even that didn't add in the GNU EH frames. That's the whole reason I needed linker script extension, or otherwise I could just use `fde-gnu-eh-frame-hdr` feature instead. This has something in common with #6

**Comment by nbdd0121** [comment]
If you are not using a baremetal linker, you can pass `--eh-frame-hdr` option and use `fde-gnu-eh-frame-hdr` feature. If you are using a baremetal linker then linker script modification would be essential (well, there are some hacks if the default linker script will keep eh-frame).

**Comment by stevefan1999-personal** [comment]
@nbdd0121 I'm using rust-lld (which should be lld with Rust quirks) since I targets to build an x86_64 kernel on an x86_64. I'm not sure if that's bare metal or not since the kernel is built on ELF and is not some arbitrary binary format (which is the .bin of those bare metal firmwares).

**Comment by nbdd0121** [comment]
I believe LLD don't have `gnu-eh-frame-hdr` so that's not an option for you.

If you are building a kernel, then you surely needs to instruct the linker to place it to a specific virtual address? Generally it's quite fragile to depend on the default linker script. I would definitely advise to use custom linker scripts and then you can put `eh_frame` modifications there.

Regardless, that's not something that I can fix or workaround in this project, so I'll be closing the issue as inactionable.
